### ISSUE TITLE
Feedback: split the first command in to commands -> easier to follow and read

### ISSUE THREAD

**Issue by thomassuedbroecker** [nheidloff/application-modernization-javaee-quarkus#4]
Hi, a very simple and small feedback: Maybe you can split the first command line into two command lines?

`$ git clone https://github.com/nheidloff/application-modernization-javaee-quarkus.git && cd application-modernization-javaee-quarkus`

I think this is simpler to read and to follow ... ;-) 
```
$ git clone https://github.com/nheidloff/application-modernization-javaee-quarkus.git
$ cd application-modernization-javaee-quarkus
```

```
$ ROOT_FOLDER=$(pwd)
$ sh ${ROOT_FOLDER}/scripts-docker/build-and-run.sh
```
Greetings,
Thomas

**Comment by nheidloff** [comment]
I guess that's a matter of personal preference :)
