### ISSUE TITLE
File with incorrect filename

### ISSUE THREAD

**Issue by TimonLukas** [nheidloff/application-modernization-javaee-quarkus#5]
Hello Niklas! I'm currently trying to follow through your tutorials. I noticed that it's not possible to clone the repository on Windows because of [this file](https://github.com/nheidloff/application-modernization-javaee-quarkus/blob/master/proxy/nginx.conf%20needed%3F) - the name isn't valid under Windows, and I'm reasonably sure it's meant to be different on other systems as well :)

**Comment by nheidloff** [comment]
Thanks Timon. I've removed it. The file wasn't used.
